channels:
- defaults
dependencies:
- python=3.7.3
- ffmpeg=4.2.2

- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19185956
  - azureml-defaults==0.1.0.19185956
  - azureml-pipeline-wrapper==0.1.0.19185956
name: project_environment
